apiVersion: apps/v1
kind: Deployment
metadata:
  name: schnauf-location
  labels:
    app: schnauf-location
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: schnauf-location
  template:
    metadata:
      labels:
        app: schnauf-location
    spec:
      imagePullSecrets:
        - name: artifactory
      containers:
        - name: schnauf-location
          image: gcr.io/main-stack-241307/location-schnauf
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: tcp-app
              containerPort: 8080
          terminationMessagePath: /dev/stdout
