version: "3.1"

services:
  mongo0:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27017:27017
    command: mongod --bind_ip_all --replSet rs0

  mongo1:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27018:27017
    command: mongod --bind_ip_all --replSet rs0

  mongo2:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27019:27017
    command: mongod --bind_ip_all --replSet rs0

  mongosetup:
    image: mongo:3.6-xenial
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/mongo_setup.sh" ]

  schnauf-command:
    image: gcr.io/main-stack-241307/schnauf-command:latest
    depends_on:
      - mongosetup
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongo0
      - MONGO_PORT=27017

  mongoUser:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27020:27017
    command: mongod --bind_ip_all

  schnauf-user:
    image: gcr.io/main-stack-241307/schnauf-user:latest
    depends_on:
      - mongoUser
    ports:
      - 9090:9090
    environment:
      - APPLICATION_PORT=9090
      - MONGO_HOST=mongoUser
      - MONGO_PORT=27020

  schnauf-query:
    image: gcr.io/main-stack-241307/schnauf-query:latest
    depends_on:
      - schnauf-command
      - schnauf-user
    ports:
      - 8090:8090
    environment:
      - APPLICATION_PORT=8090
      - SCHNAUF_COMMAND_HOST=schnauf-command
      - SCHNAUF_COMMAND_PORT=8080
      - SCHNAUFR_HOST=schnauf-user
      - SCHNAUFR_PORT=9090
