apiVersion: apps/v1
kind: Deployment
metadata:
  name: schnauf-user
  labels:
    app: schnauf-user
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: schnauf-user
  template:
    metadata:
      labels:
        app: schnauf-user
    spec:
      imagePullSecrets:
        - name: artifactory
      containers:
        - name: schnauf-user
          image: gcr.io/main-stack-241307/schnauf-user
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: tcp-app
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: schnauf-user-config
          terminationMessagePath: /dev/stdout
        - name: mongo
          image: mongo:3.6-xenial
          ports:
            - containerPort: 27017