apiVersion: v1
kind: Service
metadata:
  name: schnaufr-user
  namespace: schnaufr-user
spec:
  selector:
    app: schnaufr-user
  type: ClusterIP
  ports:
    - name: tcp-app
      port: 8080
      targetPort: 8080
