apiVersion: apps/v1
kind: Deployment
metadata:
  name: schnaufr-query
  namespace: schnaufr-query
  labels:
    app: schnaufr-query
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: schnaufr-query
  template:
    metadata:
      labels:
        app: schnaufr-query
    spec:
      imagePullSecrets:
        - name: artifactory
      containers:
        - name: schnaufr-query
          imagePullPolicy: Always
          image: gcr.io/main-stack-241307/schnaufr-query
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
          envFrom:
            - configMapRef:
                name: schnaufr-query-config
          ports:
            - name: tcp-app
              containerPort: 8080
          terminationMessagePath: /dev/stdout
