version: "3.1"

services:
  mongo:
    image: mongo:3.4-xenial
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/data:/data/db

  schnauf-command:
    image: schnauf-command:0.1.0-SNAPSHOT
    depends_on:
      - mongo
    ports:
      - 8080:8080
