version: "3.1"

services:
  mongo0:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27017:27017
    command: mongod --bind_ip_all --replSet rs0

  mongo1:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27018:27017
    command: mongod --bind_ip_all --replSet rs0

  mongo2:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27019:27017
    command: mongod --bind_ip_all --replSet rs0

  mongosetup:
    image: mongo:3.6-xenial
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/mongo_setup.sh" ]

  schnauf-command:
    image: schnauf-command:0.1.0-SNAPSHOT
    depends_on:
      - mongosetup
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongo0

  schnauf-query:
    image: gcr.io/main-stack-241307/query-schnauf:latest
    depends_on:
      - schnauf-command
    ports:
      - 8090:8090
    environment:
      - APPLICATION_PORT=8090
      - SCHNAUF_COMMAND_HOST=schnauf-command
      - SCHNAUF_COMMAND_PORT=8080
