apiVersion: v1
kind: Service
metadata:
  name: schnaufr-schnauf
  namespace: schnaufr-schnauf
spec:
  selector:
    app: schnaufr-schnauf
  type: ClusterIP
  ports:
    - name: tcp-app
      port: 8080
      targetPort: 8080
