apiVersion: v1
kind: Service
metadata:
  name: schnaufr-schnauf
  namespace: schnaufr-schnauf
spec:
  selector:
    app: schnaufr-schnauf
  type: LoadBalancer
  ports:
    - name: tcp-app
      port: 8080
      targetPort: 8080
  loadBalancerIP: 35.246.79.96 # gcloud compute addresses create schnaufr --region europe-west2
